[package]
name = "tokio-webserver"
version = "0.0.1"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
config ="0.10"
serde = {version = "1.0", features = ["derive"]}
lazy_static = "1.4"
warp = "0.3"
